// Generated by CoffeeScript 1.10.0
(function() {
  define(function(require, exports, module) {
    exports.getCompletions = function(editor, session, pos, prefix, callback) {
      var wordList;
      wordList = ['\\item'];
      return callback(null, wordList.map(function(word) {
        return {
          caption: word,
          value: word,
          meta: 'TEX'
        };
      }));
    };
  });

}).call(this);
