// Generated by CoffeeScript 1.10.0
(function() {
  var kek;

  kek = function(a) {
    if (a == null) {
      a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];
    }
    console.log(1);
    return console.log(a.length);
  };

}).call(this);
