// Generated by CoffeeScript 1.10.0
(function() {
  var reverse;

  reverse = function(str) {
    var i, j, ref, results, temp;
    results = [];
    for (i = j = 0, ref = str.length % 2; 0 <= ref ? j <= ref : j >= ref; i = 0 <= ref ? ++j : --j) {
      temp = str[i];
      str[i] = str[str.length - i];
      results.push(str[str.length - i] = temp);
    }
    return results;
  };

  $("#button").click(function() {
    var a;
    a = $("#a").val();
    return $("#c").html(a);
  });

}).call(this);
